name: ringdown
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37_1000
  - arviz=0.4.1=py_0
  - asn1crypto=0.24.0=py37_1003
  - astropy=3.2.1=py37h01d97ff_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - boost-cpp=1.70.0=h75728bb_2
  - boto=2.49.0=py_0
  - bzip2=1.0.8=h01d97ff_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cctools=895=1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37hccf1714_0
  - cfitsio=3.470=h389770f_2
  - cftime=1.0.3.4=py37h1e5eb4f_1001
  - chardet=3.0.4=py37_1003
  - chealpix=3.30.0=ha7c7693_1002
  - clang=8.0.1=h770b8ee_0
  - clang_osx-64=8.0.1=h22b1bf0_18
  - clangxx=8.0.1=0
  - clangxx_osx-64=8.0.1=h22b1bf0_18
  - click=7.0=py_0
  - compiler-rt=8.0.1=hef50cfd_0
  - configobj=5.0.6=py_0
  - corner=2.0.1=py_1001
  - cryptography=2.7=py37h212c5bf_0
  - curl=7.65.3=h22ea746_0
  - cycler=0.10.0=py_1
  - cython=0.29.13=py37h6de7cb9_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - fftw=3.3.8=nompi_h5c49c53_1109
  - flask=0.12.4=py_0
  - flask-cache=0.13.1=py_1000
  - flask-sqlalchemy=2.4.0=py_0
  - freetype=2.10.0=h24853df_1
  - future=0.17.1=py37_1000
  - geos=3.7.2=h6de7cb9_1
  - gsl=2.5=ha2d443c_1
  - h5py=2.9.0=nompi_py37h3d62f72_1103
  - hdf4=4.2.13=hf3c6af0_1002
  - hdf5=1.10.4=nompi_h0cbb7df_1106
  - healpy=1.12.9=py37h2c3d0c3_1
  - icu=64.2=h6de7cb9_1
  - idna=2.8=py37_1000
  - importlib_metadata=0.20=py37_0
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=1.1.0=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py_0
  - jpeg=9c=h1de35cc_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=1.1.1=py_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py37h770b8ee_0
  - krb5=1.16.3=hcfa6398_1001
  - lal=6.20.2=fftw_h035cc09_105
  - lalapps=6.24.0=py37h3ed4614_2
  - lalburst=1.5.2=hba1f1f8_1
  - lalframe=1.4.5=h01d97ff_0
  - lalinference=1.11.2=hc66d1d9_0
  - lalinspiral=1.9.0=hba1f1f8_1
  - lalmetaio=1.5.1=h01d97ff_0
  - lalpulsar=1.18.1=h607212f_0
  - lalsimulation=1.9.1=hba1f1f8_0
  - lalsuite=6.57=py37_0
  - ld64=274.2=h7c2db76_0
  - ldas-tools-al=2.6.2=he3f880d_1003
  - ldas-tools-framecpp=2.6.5=he3f880d_1004
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=8.0.1=0
  - libcxxabi=8.0.1=0
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libframe=8.33=h01d97ff_0
  - libgfortran=3.0.1=0
  - liblapack=3.8.0=12_openblas
  - libllvm8=8.0.1=h770b8ee_0
  - libnetcdf=4.6.2=h6b88ef6_1001
  - libopenblas=0.3.7=hd44dcd8_1
  - libpng=1.6.37=h2573ce8_0
  - libpq=11.5=h756f0eb_1
  - libsodium=1.0.17=h01d97ff_0
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.0.10=hd08fb8f_1003
  - ligo-common=1.0.3=py_0
  - ligo-segments=1.2.0=py37h1de35cc_0
  - llvm-lto-tapi=4.0.1=h6701bc3_0
  - llvm-openmp=8.0.1=h770b8ee_0
  - lscsoft-glue=2.0.0=py37h1de35cc_0
  - lz4-c=1.8.3=h6de7cb9_1001
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h3a684a6_1
  - metaio=8.5.1=ha441bb4_1000
  - mistune=0.8.4=py37h1de35cc_1000
  - more-itertools=7.2.0=py_0
  - mpi=1.0=openmpi
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - netcdf4=1.5.1.2=py37h58b02fa_0
  - notebook=6.0.1=py37_0
  - numpy=1.17.1=py37h6b0580a_0
  - olefile=0.46=py_0
  - openmpi=4.0.1=ha90c164_2
  - openssl=1.1.1c=h01d97ff_0
  - packaging=19.0=py_0
  - pamela=1.0.0=py_0
  - pandas=0.25.1=py37h86efe34_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.1.0=py37h75ffe9a_1
  - pip=19.2.3=py37_0
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py37h01d97ff_0
  - psycopg2=2.8.3=py37h212c5bf_0
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyrsistent=0.15.4=py37h01d97ff_0
  - pysocks=1.7.0=py37_0
  - pystan=2.17.1.0=py37h1702cab_1003
  - pytest=5.1.2=py37_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.5.0=py_0
  - pytest-doctestplus=0.3.0=py_1
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.1=py_0
  - pytest-runner=5.1=py_0
  - python=3.7.3=h93065d6_1
  - python-dateutil=2.8.0=py_0
  - python-lal=6.20.2=fftw_py37h962a6d8_105
  - python-lalburst=1.5.2=py37heacc8b8_1
  - python-lalframe=1.4.5=py37h1e5eb4f_0
  - python-lalinference=1.11.2=py37h01d97ff_0
  - python-lalinspiral=1.9.0=py37heacc8b8_1
  - python-lalmetaio=1.5.1=py37h01d97ff_0
  - python-lalpulsar=1.18.1=py37h1c7146f_0
  - python-lalsimulation=1.9.1=py37h01d97ff_0
  - python-ligo-lw=1.5.3=py37h1de35cc_0
  - python-pegasus-wms=4.9.1=py_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h01d97ff_0
  - pyzmq=18.0.2=py37hee98d25_2
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py37_1
  - scipy=1.3.1=py37hab3da7d_2
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py37_0
  - shapely=1.6.4=py37h0567c5e_1006
  - six=1.12.0=py37_1000
  - sqlalchemy=1.3.8=py37h01d97ff_0
  - sqlite=3.29.0=hb7d70f7_1
  - statsmodels=0.10.1=py37heacc8b8_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h2573ce8_1002
  - tornado=6.0.3=py37h01d97ff_0
  - traitlets=4.3.2=py37_1000
  - urllib3=1.25.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.15.5=py_0
  - wheel=0.33.6=py37_0
  - xarray=0.12.3=py_0
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h01d97ff_1005
  - zstd=1.4.0=ha9f0a20_0
  - pip:
    - llvmlite==0.29.0
    - numba==0.45.1
    - qnm==5.0.6
    - tqdm==4.35.0
prefix: /Users/wfarr/anaconda3/envs/ringdown

